# **Numpy**


In [1]:
#importing
import numpy as np #numpy kütüphanesi import edilip kısayol olarak np kullanılır.

In [2]:
array = np.array([1,2,3]) #numpy'ın array methodu çağrılıp array oluşturulur.
                          #1*3 vector oluşturuldu
#numpy vektör ya da matris oluşturarak matematiksel işlemleri hızlı bir şekilde yapar.
print(array)

[1 2 3]


In [3]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array2.shape) #array'ın shape'ine bakılır. 
                    #(15,) -> 15'e 1'lik bir vektör

(15,)


In [4]:
a = array2.reshape(3,5) 
#oluşturulan vektör 3 satır 5 sütunluk matrise dönüştürüldü.
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
print("shape: ",a.shape) #(3, 5)

print("dimension: ",a.ndim) #oluşturulan matrisin boyutuna bakılır.
                            #dimension:  2

print("data type: ",a.dtype.name) #data type:  int32
#array'in içindeki verilerin datatype'larını öğrenmek için (float,string,integer) bu method kullanılır

print("size: ",a.size) #reshape'ten önceki boyutu verilir.
                       #size:  15
                       
print("type",type(a))  #type <class 'numpy.ndarray'>

shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type <class 'numpy.ndarray'>


In [6]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #reshape yapmadan da boyutu değiştirilebilir.

In [7]:
print(array3) #array([[ 1,  2,  3,  4],
                     #[ 5,  6,  7,  8],
                     #[ 9, 10, 11, 12]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(array3.shape) #(3, 4)

(3, 4)


In [9]:
zeros= np.zeros((3,4)) #3 satır 4 sütunluk sıfırlardan oluşan array yaratılır.
#bu matris ile memoryde yer ayırtılır, güncelleme yapılmak istendiğinde güncellenir.
#append gibi fonksiyonlar memory'iyi yorar ve programı yavaşlatır.
#o yüzden bu method tercih edilir.

In [10]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
np.ones((3,4)) #1'lerden oluşan 3*4'lük bir matris yaratır.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty((4,5)) #boş bir array oluşturulur.

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810879e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.24611674e-306, 1.29061821e-306],
       [6.23057349e-307, 1.29062025e-306, 6.89807188e-307,
        2.22522596e-306, 0.00000000e+000]])

In [13]:
np.arange(10,50,5) #10 ve 50 arasındaki sayılar 5'er 5'er yazdırılır.
#array([10, 15, 20, 25, 30, 35, 40, 45])

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
a= np.linspace(0,10,20) #0 ile 10 arasında 20 tane sayı yazdırılır.
#array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
#       2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
#       5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
#       7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [16]:
#numpy basic operations
a= np.array([1,2,3])
b= np.array([4,5,6]) #toplama çıkarma gibi işlemlerde boyutlarının aynı olması önemlidir.

print(a+b) #[5 7 9]
print(a-b) #[-3 -3 -3]
print(a**2) #[1 4 9]

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [15]:
#arraylerde saymaya sıfırdan başlanır.
a= np.array([1,2,3,4,5,6,7]) #vektor -> dimension 1

In [23]:
liste = [1,2,3,4]

array = np.array([5,6,7,8])
#array tanımlamak için array'in içine liste yazılır.
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [24]:
array = np.array(liste)
print(array)

[1 2 3 4]


In [25]:
liste2 = list(array) #arrayden listeye geçilir.
print(liste2)

[1, 2, 3, 4]


In [29]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [31]:
b=a

c=a

b[0]=5 #bu örnekte a,b,c arraylerinin hepsinin 0. indeksi değişir.
#bunun sebebi np.array memory'de bir değer olarak değil bir alan olarak depolanır.
#a,b,c için memory aynı alan ayrıldığından bir tanesi değiştirilince hepsi değişir.
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [30]:
d = a.copy() #copy methoduyla memory yeni bir alan tahsis edilir.
#böylelikle birinin bir indeksi değişince diğerleri bundan etkilenmez.

[1 2 3]


In [34]:
a= np.array([1,2,3,4,5,6,7]) #vector -> dimension 1
print(a)

[1 2 3 4 5 6 7]


In [35]:
print(a[0]) #arraydeki 1 sayısını verir.

1


In [36]:
print(a[0:4]) #ilk 4 indeksi yazdırır.

[1 2 3 4]


In [38]:
reverse_array = a[::-1] #array'i ters çevirir.
print(reverse_array)

[7 6 5 4 3 2 1]


In [5]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
print(b[1,1]) #1.satır 1.sütundaki değer olan 7'yi verir.

print(b[:,1]) #satırların hepsini ve 2. sütunu verir. [2 7]

print(b[1,:]) #2.satırdaki elemanların tamamını verir. [ 6  7  8  9 10]

print(b[1,1:4]) #2.satır 2. 3. 4. sütunları verir. [7 8 9]

print(b[-1,:]) #son satır ve tüm sütunları alır. [ 6  7  8  9 10]

print(b[:,-1]) #son sütun ve tüm satırlari alır. [ 5 10]

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [42]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3*3'lük array oluşturuldu.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
a = array.ravel() #ravel methoduyla tek boyutlu hale getirilir.
print(a)

[1 2 3 4 5 6 7 8 9]


In [44]:
array2 = a.reshape(3,3) #tekrardan 3*3'lük array haline getirildi.
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
array_transpose = array2.T #array'in transpose'u alınır.
                           #array([[1, 4, 7],
                                  #[2, 5, 8],
                                  #[3, 6, 9]])
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [46]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
array3.resize((2,3)) #resize ile yapılan boyut değişimleri kalıcıdır, aynı array'in içine kaydeder.
#reshape ile yapılan değişimler kalıcı değildir. yapılan değişim başka bir değişkene kaydedilmelidir.
print(array3)

[[1 2 3]
 [4 5 6]]
